core/urls.py
# from django.conf import settings
# from django.conf.urls.static import static
from django.urls import path
from django.views.generic.base import RedirectView, TemplateView

from core import views

app_name = 'core'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),

    # Redirections
    path('docs/', RedirectView.as_view(url='https://docs.slackware.com/'),
         name='docs'),
    path('docs/beginners-guide/',
         RedirectView.as_view(
             url='https://docs.slackware.com/slackware:beginners_guide'),
         name='beginners-guide'),
    path('docs/installation-guide/',
         RedirectView.as_view(
             url='https://docs.slackware.com/slackware:install'),
         name='installation-guide'),
    path('download/', RedirectView.as_view(url='/get-slack/'),
         name='download'),
    path('favicon.ico', RedirectView.as_view(url='static/img/favicon.ico',
                                             permanent=True),
         name='favicon'),
    path('getslack/', RedirectView.as_view(url='/get-slack/'),
         name='getslack'),
    path('humans.txt', TemplateView.as_view(template_name="core/humans.txt",
                                            content_type='text/plain'),
         name='humans'),
    path('packages/',
         RedirectView.as_view(url='https://packages.slackware.com/'),
         name='packages'),
    path('planet/', RedirectView.as_view(url='https://planet.slackware.com'),
         name='planet'),
    path('slackbook/',
         RedirectView.as_view(url='https://www.slackbook.org/beta/'),
         name='slackbook'),

    # Page detail
    path('<slug:page_slug>/',
         views.PageDetailView.as_view(),
         name='page-detail'),
    # Sub Page detail
    path('<slug:parent_slug>/<slug:page_slug>/',
         views.SubPageDetailView.as_view(),
         name='subpage-detail'),
]
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

import mistune
from pygments import highlight
from pygments.formatters import html
from pygments.lexers import get_lexer_by_name


class HighlightRenderer(mistune.Renderer):
    def block_code(self, code, lang):
        if not lang:
            return '\n<pre><code>%s</code></pre>\n' % mistune.escape(code)

        lexer = get_lexer_by_name(lang, stripall=True)
        formatter = html.HtmlFormatter()
        return highlight(code, lexer, formatter)


renderer = HighlightRenderer()
markdown = mistune.Markdown(renderer=renderer)


class Taxonomy(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    content = models.TextField()

    class Meta:
        abstract = True


class Tag(Taxonomy):
    def __str__(self):
        return self.title


class Post(models.Model):
    """Post abstract class"""

    # Post status
    PUBLISHED_STATUS = 'published'
    DRAFT_STATUS = 'draft'
    STATUS_CHOICES = (
        (PUBLISHED_STATUS.lower(), PUBLISHED_STATUS.title()),
        (DRAFT_STATUS.lower(), DRAFT_STATUS.title())
    )
    STATUS_CHOICES = sorted(STATUS_CHOICES)

    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.PROTECT)
    title = models.CharField(max_length=500)
    slug = models.SlugField(unique=True, max_length=200)
    content = models.TextField()
    content_html = models.TextField(editable=False)
    is_public = models.BooleanField(default=True)
    status = models.CharField(choices=STATUS_CHOICES, default=PUBLISHED_STATUS,
                              max_length=9)
    tags = models.ManyToManyField(Tag, blank=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    pub_date = models.DateTimeField(default=timezone.now)
    last_modified = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.content_html = markdown(self.content)
        super().save(*args, **kwargs)

    class Meta:
        abstract = True
        # https://docs.djangoproject.com/en/3.2/ref/models/options/#ordering
        ordering = ('-pub_date',)


class Page(Post):
    """Page model"""
    parent = models.ForeignKey('Page', on_delete=models.SET_NULL,
                               limit_choices_to={'parent': None},
                               blank=True, null=True)

    def __str__(self):
        return self.title

core/views.py
from django.db.models import Q
from django.shortcuts import redirect, render
from django.utils import timezone
from django.views.generic import DetailView, ListView

from core.models import Page, Post
from weblog.models import Entry

RECENTLY = 5


class IndexView(ListView):
    template_name = 'core/index.html'
    paginate_by = RECENTLY

    def get_queryset(self):
        return PostList.get_page_list()[:RECENTLY]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_entry_list'] = Entry.objects.filter(
            Q(status=Post.PUBLISHED_STATUS),
            Q(pub_date__date__lte=timezone.now())
        )[:RECENTLY]
        context['latest_page_list'] = PostList.get_page_list()[:RECENTLY]
        return context


class PageDetailView(DetailView):
    """Page detail"""
    model = Page
    slug_url_kwarg = 'page_slug'
    context_object_name = 'page'

    def get(self, request, *args, **kwargs):
        page = PostList.get_page_list().get(slug=self.kwargs['page_slug'])

        if page.parent is not None:
            return redirect(f'/{page.parent.slug}/{page.slug}/')

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class SubPageDetailView(DetailView):
    """Sub Page detail"""
    model = Page
    slug_url_kwarg = 'page_slug'

    def get(self, request, *args, **kwargs):
        page = PostList.get_page_list().get(
            slug=self.kwargs['page_slug'],
            parent__slug=self.kwargs['parent_slug'])
        return render(request, template_name='core/page_detail.html',
                      context={'page': page})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class PostList():
    """Post list"""

    def get_page_list():
        """Page list"""
        return Page.objects.filter(
            Q(status=Post.PUBLISHED_STATUS),
            Q(pub_date__date__lte=timezone.now())
        )

core/templates/core/base.html
<!DOCTYPE html>{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>The Slackware Linux Project</title>
  <meta name="description" content="The Slackware Linux Project. The Slackware Linux distribution is a complete multitasking UNIX-like operating system. Slackware is an open source independent Linux-based operating system with the main goals of being stable and easy-to-use by novice and experienced users alike. It is one of the oldest GNU/Linux distributions on the world.">
  <meta name="keywords" content="slackware, slackware linux, linux">
  {# <link rel="stylesheet" href="{% static 'css/bootstrap-5.1.1.min.css' %}"> #}
  <link rel="stylesheet" href="{% static 'css/fontawesome-free-5.15.4.min.css' %}">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="shortcut icon" type="image/jpg" href="{% static 'img/favicon.ico' %}"/>
  <link type="text/plain" rel="author" href="{% url 'core:humans' %}">
</head>
<body>
{% include "core/navbar.html" %}

  {% block content %}
  <div class="jumbotron">
    <div class="content">
      <div class="jumbotron-block">
        <div class="jumbotron-item">
          <h1>The Slackware Linux Project</h1>
          <p>
            The Slackware Linux Project has aimed at producing the most "UNIX-like"
            Linux distribution out there. Slackware complies with the published
            Linux standards, such as the Linux File System Standard. We have always
            considered simplicity and stability paramount, and as a result Slackware
            has become one of the most popular, stable, and friendly distributions
            available.
          </p>
        </div>
        <div class="jumbotron-image">
          <img src="{% static 'img/Slackware-mascot.svg' %}" alt="Slackware mascot" class="h-52 lg:h-44 xl:h-40">
        </div>
      </div>
      <div class="jumbotron-button">
        <a class="btn btn-slack" href="/get-slack/">
          <i class="fas fa-download"></i> Get Slackware 15.0
        </a>
        <a class="btn btn-slack-outline" href="/about/">
          <i class="fas fa-angle-right"></i> About Slackware
        </a>
      </div>
    </div>
  </div>

  <div class="featured content">
    <div class="featured-item pr-1">
      <h2><i class="fas fa-clipboard-list"></i> Get Started</h2>
      <p>If you installed Slackware for the first time, you may be daunted by the sight of the blinking cursor at a console login.</p>
      <p><a href="{% url 'core:beginners-guide' %}">Read the Beginner&rsquo;s Guide</a></p>
    </div>
    <div class="featured-item pl-1 lg:pr-1">
      <h2><i class="fas fa-download"></i> Download</h2>
      <p>Get the latest stable version of Slackware Linux operating system through bitorrent or from one of our HTTP and FTP mirrors.</p>
      <p>Latest: <a href="/get-slack/">Slackware 15.0</a></p>
    </div>
    <div class="featured-item pr-1 lg:pl-1">
      <h2><i class="fas fa-book"></i> Docs</h2>
      <p>Documentation for Slackware Linux operating system, along with tutorials and guides, are available in our SlackDocs webpage.</p>
      <p><a href="{% url 'core:docs' %}">docs.slackware.com</a></p>
    </div>
    <div class="featured-item pl-1">
      <h2><i class="fas fa-box-open"></i> Packages</h2>
      <p>Slackware Linux Official package set provides a good, stable, and flexible operating system (and is quite adequate for many individuals).</p>
      <p><a href="{% url 'core:packages' %}">packages.slackware.com</a></p>
    </div>
  </div>

  <div class="latest-news content">
    <div class="post-item">
      <h2><i class="far fa-newspaper"></i> Latest News</h2>
      <ul>
        {% for entry in latest_entry_list %}
        <li class="list-group-item">
          <span class="list-item-date">{{ entry.pub_date|date:'Y-m-d' }}</span>
          <a class="list-item-link" href="{{ entry.get_absolute_url }}">
            {{ entry.title }}
          </a>
        </li>
        {% endfor %}
      </ul>
    </div>
    <div class="post-item">
      <h2><i class="fas fa-shield-alt"></i> Security Advisories</h2>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <span class="list-item-date">2021-08-31</span>
          <a class="list-item-link" href="">ntfs-3g (SSA:2021-243-01)</a>
        </li>
        <li class="list-group-item">
          <span class="list-item-date">2021-07-21</span>
          <a class="list-item-link" href="">curl (SSA:2021-202-02)</a>
        </li>
        <li class="list-group-item">
          <span class="list-item-date">2021-07-20</span>
          <a class="list-item-link" href="">Slackware 14.2 kernel (SSA:2021-202-01)</a>
        </li>
        <li class="list-group-item">
          <span class="list-item-date">2021-06-07</span>
          <a class="list-item-link" href="">polkit (SSA:2021-158-02)</a>
        </li>
        <li class="list-group-item">
          <span class="list-item-date">2021-06-07</span>
          <a class="list-item-link" href="">httpd (SSA:2021-158-01)</a>
        </li>
      </ul>
    </div>
    <div class="post-item">
      <h2><i class="far fa-list-alt"></i> Changelog</h2>
      <ul>
        <li class="list-group-item">
          <span class="list-item-date">2021-08-31</span>
          <a class="list-item-link" href="">zntfs-3g-2021.8.22-i586-1_slack14.2.txz</a>
        </li>
        <li class="list-group-item">
          <span class="list-item-date">2021-07-21</span>
          <a class="list-item-link" href="">zcurl-7.78.0-i586-1_slack14.2.txz</a>
        </li>
        <li class="list-group-item">
          <span class="list-item-date">2021-07-21</span>
          <a class="list-item-link" href="">zlinux-4.4.276/*</a>
        </li>
        <li class="list-group-item">
          <span class="list-item-date">2021-06-07</span>
          <a class="list-item-link" href="">zhttpd-2.4.48-i586-1_slack14.2.txz</a>
        </li>
        <li class="list-group-item">
          <span class="list-item-date">2021-06-07</span>
          <a class="list-item-link" href="">zlibX11-1.7.2-i586-1_slack14.2.txz</a>
        </li>
      </ul>
    </div>
  </div>
  {% endblock content %}

{% include "core/get_slack.html" %}

{% include "core/footer.html" %}
  {# <script src="{% static 'js/bootstrap-5.1.1.min.js' %}"></script> #}
</body>
</html>

core/templates/core/base_page.html
{% extends "core/base.html" %}

core/templates/core/footer.html
  <footer class="footer">
    <div class="content">
      <div class="footer-items">
        <div class="footer-item">
          <h5>Slackware Linux</h5>
          <ul>
            <li><a href="/about/">About</a></li>
            <li><a href="/contact/">Contact</a></li>
            <li><a href="/trademark/">Registered Trademark</a></li>
            <li><a href="/faq/">FAQ</a></li>
          </ul>
        </div>
        <div class="footer-item">
          <h5>Getting Slack</h5>
          <ul>
            <li><a href="/get-slack/">Get Slack</a></li>
            <li><a href="{% url 'core:packages' %}">Packages</a></li>
            <li><a href="/ports/">Ports/Architectures</a></li>
          </ul>
        </div>
        <div class="footer-item">
          <h5>News</h5>
          <ul>
            <li><a href="/weblog/">Weblog</a></li>
            <li><a href="/changelog/">ChangeLogs</a></li>
            <li><a href="{% url 'core:planet' %}">Slackware Planet</a></li>
          </ul>
        </div>
        <div class="footer-item">
          <h5>Documentation</h5>
          <ul>
            <li><a href="{% url 'core:docs' %}">Slackware Docs</a></li>
            <li><a href="{% url 'core:slackbook' %}">SlackBook</a></li>
            <li><a href="{% url 'core:installation-guide' %}">Installation Guide</a></li>
            <li><a href="{% url 'core:beginners-guide' %}">Post-Install Guide</a></li>
          </ul>
        </div>
        <div class="footer-item">
          <h5>Support</h5>
          <ul>
            <li><a href="/lists/">Mailing Lists</a></li>
            <li><a href="/security/">Security Advisories</a></li>
            <li><a href="/links/">Other Sites</a></li>
          </ul>
        </div>
      </div>
      <div class="footer-copy">
        Slackware &reg; is a <a href="/trademark/">registered trademark</a> of Slackware Linux, Inc. All logos
        and graphics are copyrighted.
      </div>
    </div>
  </footer>

core/templates/core/get_slack.html
  <div class="get-slack">
    <div class="get-slack-content">
      <div class="get-slack-item">
        <h2>Slackware 15.0</h2>
        <p>Download the latest stable release of Slackware Linux.</p>
      </div>
      <div class="get-slack-btn">
        <a class="btn btn-slack" href="/get-slack/">
          <i class="fas fa-download"></i> Get Slackware 15.0
        </a>  
      </div>
    </div>
  </div>

core/templates/core/index.html
{% extends "core/base.html" %}

core/templates/core/navbar.html
{% load static %}
  <nav class="navbar">
    <div class="navbar-content">
      <a class="" href="/">
        <img src="{% static 'img/Slackware_web_logo.svg' %}" alt="Slackware Linux logo" class="navbar-logo">
      </a>
      <button class="navbar-toggler" type="button">
        <span class="navbar-toggler-icon text-2xl">&equiv;</span>
      </button>
      <div class="navbar-collapse">
        <ul class="navbar-items">
          <li class="navbar-item">{% url 'core:index' as home %}
            <a class="navbar-link {% if request.path == home %}active{% endif %}" aria-current="page" href="{{ home }}">Home</a>
          </li>
          <li class="navbar-item">
            <a class="navbar-link {% if request.path == '/about/' %}active{% endif %}" href="/about/">About</a>
          </li>
          <li class="navbar-item">
            <a class="navbar-link {% if request.path == '/get-slack/' %}active{% endif %}" href="/get-slack/">Get Slack</a>
          </li>
          <li class="navbar-item">
            <a class="navbar-link {% if request.path == '/docs/' %}active{% endif %}" href="/docs/">Documentation</a>
          </li>
          <li class="navbar-item">
            <a class="btn btn-donate" href="/donate/"><i class="fas fa-hand-holding-usd"></i> Donate</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

core/templates/core/page_detail.html
{% extends "core/base_page.html" %}
{% block content %}
<div class="bg-slack">
  <div class="content">
    <div class="post-title">
      <h1 class="">{{ page.title }}</h1>
    </div>    
  </div>
</div>

<div class="post-content">
  {{ page.content_html | safe }}
</div>
{% endblock content %}